apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    name: hello-world
    app: hello-world
    environment: test
spec:
  containers:
  - name: hello-world
    image: nginxdemos/hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
